name: TDP Notebook Unittesting
run-name: workflow run by ${{ github.actor }}

on: 
    # workflow_dispatch:
    push:
        paths:
        - "folder-to-watch/**"

  # pull_request:
  #   branches-ignore:
  #     - 'main'
  #   types: [opened, reopened, synchronize]

permissions:
  contents: write

env:
  PUSH_CHANGES: true

jobs:
  run-notebook-unittests:
    runs-on: windows-latest
    name: Pass Vars Test workfloq

    steps:
      - run: echo "Branch name is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: checkout feature branch
        uses: actions/checkout@v4

      - name: load variables
        id: load-variables
        shell: pwsh
        run: |
          $variables = Get-content -Raw "./variables/variables_devl.yml"
          Write-Host("[DEBUG] $variables")
          $variables.GetEnumerator() | ForEach-Object {
            $name = $_.key 
            $value = $_.value
            echo "$name=$value" >> $ENV:GITHUB_ENV
            Write-Host("[DEBUG] $name=$value")
          }

      - name: set env vars
        id: set-env-vars
        run: |
            $changes = 10
            echo "changes=$changes" >> $ENV:GITHUB_ENV
            echo "FOO=yeah" >> $ENV:GITHUB_OUTPUT
            echo "BAR=nah" >> $ENV:GITHUB_OUTPUT

      - name: Use env var
        run: |
          echo "getting env vars"
          echo ${{ env.changes }}
          echo ${{ steps.set-env-vars.outputs.FOO }}
          echo ${{ steps.set-env-vars.outputs.BAR }}
